---
- name: Install dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
 
- name: Add Docker CE repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "0644"
 
- name: Install Docker packages
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: present
 
